# Generated by Django 5.0.6 on 2024-07-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('ISO2', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['ISO2'], name='ISO2_idx')],
            },
        ),
    ]
