# Generated by Django 5.0.6 on 2024-07-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['seller_id'], name='seller_id_idx')],
            },
        ),
    ]
