# Generated by Django 5.0.6 on 2024-07-04 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('order_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(max_length=100)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.seller')),
            ],
            options={
                'indexes': [models.Index(fields=['order_number'], name='order_number_idx')],
            },
        ),
    ]
