# Generated by Django 5.0.6 on 2024-07-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='seller',
        ),
        migrations.AddField(
            model_name='sale',
            name='sellers',
            field=models.ManyToManyField(to='sellers.seller'),
        ),
    ]
